### ISSUE TITLE
Acces denied (file not found) on dictionnary folder

### ISSUE THREAD

**Issue by flenoir** [sandflow/regxmllib#141]
Hi, 

 I try to use regxmlib to dump MXF datas to xml file but i get an error while i try to submit the dictionnary folder containing all dictionnaries in .xml

my command is ``` $  java -cp /c/qc/regxmllib-1.1.3.jar com.sandflow.smpte.tools.RegXMLDump -all -d /c/qc/dict/ -i /c/qc/as10_10s.mxf ```

and terminal is returning :

```
Exception in thread "main" java.io.FileNotFoundException: C:\qc\dict (Acces denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at com.sandflow.smpte.tools.RegXMLDump.main(RegXMLDump.java:179)
```
but it seems that my right are ok on this folder 👍 
``` $ ls -ll
total 74184
-rw-r--r-- 1 Fabien 197121 75034184 déc.   9  2015 as10_10s.mxf
drwxr-xr-x 1 Fabien 197121        0 juin  26  2018 dict/
drwxr-xr-x 1 Fabien 197121        0 sept. 25 14:52 dict2/
-rw-r--r-- 1 Fabien 197121     2219 sept. 25 14:50 ElementsRegister.xsd
-rw-r--r-- 1 Fabien 197121     3422 sept. 25 14:50 GroupsRegister.xsd
-rw-r--r-- 1 Fabien 197121     1793 sept. 25 14:49 LabelsRegister.xsd
-rw-r--r-- 1 Fabien 197121   457185 juin   1  2018 old_regxmllib-1.1.1.jar
-rw-r--r-- 1 Fabien 197121   440306 sept. 25 15:09 regxmllib-1.1.3.jar
drwxr-xr-x 1 Fabien 197121        0 sept. 25 14:50 smpte/
-rw-r--r-- 1 Fabien 197121     4014 sept. 25 14:50 TypesRegister.xsd
```

I also did try to  register Dict but my syntaxe 
```
java -cp /c/qc/regxmllib-1.1.3.jar com.sandflow.smpte.tools.XMLRegistersToDict -e /c/qc/smpte/ElementsRegister.xsd -g /c/qc/smpte/GroupsRegister.xsd -l /c/qc/smpte/LabelsRegister.xsd -t /c/qc/smpte/TypesRegister.xsd /c/qc/dict2/

```

does not seems to be ok because dict2 folder is never fullfilled and i just get this terminal output

```
Converts XML Registers to RegXML metadictionary.
  Usage: XMLRegistersToDict -e elementsregspath
                            -l labelsregpath
                            -g groupsregpath
                            -t typesregpath
                            outputdir
         XMLRegistersToDict -?
```

**Comment by palemieux** [comment]
> `/c/qc/dict/`

Can you provide more information on your runtime environment, i.e. OS, etc.
